# config/sim_config.yaml

friction:
  plane: 0.1 # 0.01
  target: 0.1 # 0.01
  robot_t: 0.0  # lateral friction
  robot_r: 0.0 # rolling friction

gravity: 9.81

mass:
  target: 10.0
  # target_moi: 2.4
  robot: 0.5

robot:
  num: 8
  init_id: [0,1,2,3,4,5,6,7]
  shape: cylinder
  radius: 0.1
  height: 0.1

target:
  size: [0.6, 0.6, 0.3]
