# config/sim_config.yaml

friction:
  plane: 1.0
  target: 0.8
  robot_t: 0.0  # lateral friction
  robot_r: 10.0 # rolling friction

mass:
  target: 10.0
  # target_moi: 2.4
  robot: 0.5

robot:
  shape: cylinder
  radius: 0.1
  height: 0.1

target:
  size: [0.6, 0.6, 0.3]
